### ISSUE TITLE
FGS.ObsEventMap

### ISSUE THREAD

**Issue by renanmav** [huaweicloud/terraform-provider-huaweicloud#1560]
### Current Terraform Version

```
$ terraform -v  
Terraform v1.0.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/huaweicloud/huaweicloud v1.25.0
```

### Use-cases

I'd like to setup OBS bucket uploads to trigger FunctionGraph execution through Terraform

https://support.huaweicloud.com/intl/en-us/tr-aos/fgs-obseventmap.html

### Attempted Solutions

Define the FunctionGraph within Terraform and create FGS.ObsEventMap manually in the HC dashboard

### Proposal

Create a "fgs_obs_event_map" resource

Take a look at this blueprint config file

```
tosca_definitions_version: huaweicloud_tosca_version_1_0
inputs:
  codeUrl:
    description: >-
      The address of the function code package on OBS. You need to upload the
      function code to OBS barrel in advance.
    label: Function
    type: string
  handler:
    default: index.handler
    description: >-
      The Execution Entry of the function. Default value is index. handler. It
      can be configured independently by code file name and entry function name.
    label: Function
    type: string
  memorySize:
    constraints:
      valid_values:
        - 128
        - 256
        - 512
        - 768
        - 1024
        - 1280
        - 1536
    default: 128
    description: The memory size of the function.
    label: Function
    type: integer
  name:
    constraints:
      regex: '^[a-zA-Z]([a-zA-Z0-9_-]*[a-zA-Z0-9])?$'
    default: image_watermark
    description: The name of the function.
    label: Function
    type: string
  runtime:
    constraints:
      valid_values:
        - Node.js6.10
        - Python2.7
        - Python3.6
        - Java8
        - Go1.8
        - Node.js8.10
    description: The runtime of the function.
    label: Function
    type: string
  timeout:
    constraints:
      in_range:
        - 3
        - 300
    default: 3
    description: The timeout of the function. The effective range is 3~300.
    label: Function
    type: integer
  xrole:
    description: The agency of the function. It should be created in advance.
    label: Function
    type: string
node_templates:
  fgsf36en:
    properties:
      codeUrl:
        get_input: codeUrl
      handler:
        get_input: handler
      memorySize:
        get_input: memorySize
      name:
        get_input: name
      role:
        get_input: xrole
      runtime:
        get_input: runtime
      timeout:
        get_input: timeout
      code: ''
      codeType: obs
    type: HuaweiCloud.FGS.Function
  fgsoe4tm:
    type: HuaweiCloud.FGS.ObsEventMap
    properties:
      eventType:
        - 'ObjectCreated:*'
        - 'ObjectRemoved:*'
      bucketName:
        get_reference: obsb17cb
      funcId:
        get_reference: fgsf36en
    requirements:
      - bucketName:
          node: obsb17cb
      - funcId:
          node: fgsf36en
  obsb17cb:
    type: HuaweiCloud.OBS.Bucket
    properties:
      acl: private
outputs:
  function-urn:
    description: function URN
    value:
      get_attribute:
        - fgsf36en
        - refID
  bucket-name:
    description: OBS bucket name
    value:
      get_attribute:
        - obsb17cb
        - refName
  obs_trigger_info:
    description: OBS trigger info
    value:
      get_attribute:
        - fgsoe4tm
        - obsEventMap
```
