### ISSUE TITLE
Can I use cloud-init with Terraform to initialize the authorized SSH keys?

### ISSUE THREAD

**Issue by alissa-tung** [huaweicloud/terraform-provider-huaweicloud#1974]
### Terraform Version
```
Terraform v1.1.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/huaweicloud/huaweicloud v1.33.0
```

### Terraform Configuration Files

```hcl
data "template_file" "user_data" {
template = file("ssh.yaml")
}

resource "huaweicloud_compute_instance" "server" {
  image_name  = "Ubuntu 20.04 server 64bit"
  user_data       = data.template_file.user_data.rendered
}
```

```yaml
# cloud init
groups:
  - ubuntu: [root, sys]
  - hashicorp

users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3N...
```

### Expected Behavior
login with `ssh terraform@(terraform output public_ip) -i $PRIVATE_KEY`

### Actual Behavior

```
The authenticity of host '***.*.***.*** (***.*.***.***)' can't be established.
ED25519 key fingerprint is SHA256:tR9*******************.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '***.*.***.***' (ED25519) to the list of known hosts.
terraform@**.*.***.***'s password: 
Permission denied, please try again.
terraform@**.*.***.***'s password: 
Permission denied, please try again.
terraform@**.*.***.***'s password: 
terraform@**.*.***.***: Permission denied (publickey,password).
```
